# Generated by Django 4.2 on 2025-08-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('summary', models.TextField(blank=True)),
                ('source', models.CharField(max_length=100)),
                ('published_at', models.DateTimeField()),
            ],
        ),
    ]
