# Generated by Django 4.2.19 on 2025-08-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_alter_news_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='summary',
            field=models.TextField(default='No summary available'),
        ),
    ]
